name: Build Image

on:
  workflow_call:
    inputs:
      registry:
        type: string
        required: true
      image:
        type: string
        required: true
      tag:
        type: string
        required: true
    secrets:
      REGISTRY_USER:
        required: true
      REGISTRY_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Login to Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | \
            docker login -u "${{ secrets.REGISTRY_USER }}" --password-stdin "${{ inputs.registry }}"

      - name: Build image
        run: |
          echo "Building image: ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.tag }}"
          docker build -t ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.tag }} .

      - name: Push image
        run: docker push ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.tag }}
